# Generated by Django 3.1.4 on 2020-12-08 04:48

import card_tracker.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('address', models.CharField(max_length=500, null=True)),
                ('lat', models.FloatField(default=0, null=True)),
                ('lon', models.FloatField(default=0, null=True)),
            ],
            options={
                'get_latest_by': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('spouse_first_name', models.CharField(blank=True, max_length=100)),
                ('spouse_last_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('lat', models.FloatField(default=0, null=True)),
                ('lon', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default=card_tracker.models.get_random_id, max_length=10, verbose_name='Card ID')),
                ('date_sent', models.DateField(default=datetime.date.today, null=True)),
                ('confirmed_receipt', models.BooleanField(default=False)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('homebase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card_tracker.homebase')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card_tracker.recipient')),
            ],
        ),
    ]
