# Generated by Django 3.1.4 on 2020-12-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebase',
            name='address_big',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='address_big',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
