# Generated by Django 3.1.4 on 2020-12-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker', '0004_auto_20201208_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='confirmed_receipt',
        ),
        migrations.AddField(
            model_name='card',
            name='recipient_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
