# Generated by Django 3.1.4 on 2020-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker', '0005_auto_20201209_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='recipient_country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
