# Generated by Django 3.1.4 on 2020-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker', '0006_auto_20201209_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='recipient_country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
