# Generated by Django 3.1.4 on 2020-12-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker', '0008_auto_20201209_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='recipient_country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
